### ISSUE TITLE
Consider dropping the PHP 7.1 support

### ISSUE THREAD

**Issue by peter279k** [maliknaik16/webthing-php#1]
As title, since the PHP 7.1 version is inactive from the official PHP development team.

And the current supported version is `PHP 7.4` version. I think it's time to let the minimum PHP version requirement be `7.4`.

The reference is available [here](https://www.php.net/supported-versions.php).

**Comment by maliknaik16** [comment]
@peter279k Thank you for opening this issue. I've updated the minimum required PHP version to `7.4`.
